services:
  db:
    image: postgres:15-alpine
    container_name: openlabs_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rr01dYZA6ltjP11lu0e2
      POSTGRES_DB: escala_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
